
PROGS := 1-self-modifying.c
#PROGS := 2-bug-self-modify.c
#PROGS += 4-derive-pc-reg.c
#PROGS += 5-derive-add.c
#PROGS := 0-ident-dcg.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

# uncomment if you want it to automatically run.
#RUN=1

include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3
